# An example config file. Modify this to define your resume(s).

# You can use yaml features like shared variables
common_skills: &common_skills
  - name: python
    level: Advanced
  - name: sql
    level: Advanced
  - name: javascript
    level: Advanced
  - name: golang
    level: Expert

# default template
# see list of templates with `cap template list` command
# or you can enter the path for your custom template. eg. "~/documents/my_resume.html"
# you can also override this parameter with the `template` parameter.
# eg `cap resume gen --template "my_template.html"`
template: "basic"

# you can define multiple resumes and one default;
resumes:
  my_resume_1:
    default: true
    profile:
      name: William H. Bonney
      email: "william.bonney@bluecolor.io"
      phone: "+902888945017"
      title: Data Engineer
      # you can add as many links as you want
      links:
        - "https://github.com/ceyhunkerti"
        - "https://github.com/bluecolor"
        - "https://en.wikipedia.org/wiki/Billy_the_Kid"
    # this field accepts markdown syntax
    summary: |
      Lorem ipsum dolor sit amet. Ut sapiente deleniti et nemo dolor sit nihil
      dolor aut repellendus repellat ad voluptas blanditiis nam nihil facilis et minus tempore?
      Qui rerum quis nam voluptas iure 33 iusto atque in ratione laudantium quo expedita animi et veniam nulla.
      - Ex provident maiores et minus soluta non voluptas temporibus.
      - Aut exercitationem architecto ea veritatis voluptates ea corrupti nesciunt ad nulla blanditiis.
      - Est saepe possimus vel deserunt consequatur.
    experiences:
      - company: ACME
        start_date: "2006"
        # you can skip `end_date` if you still work in this project/job.
        end_date: "2010"
        title: "Data Engineer"
        # chips/skills you wan't to highlight in this experience
        tags: [python, scala, sql]
        # this field accepts markdown syntax
        summary: |
          - You can enter markdown items
          - I've this thing
          - I've done another thing
          - Also I've done this thing
      - company: Chocolate Factory
        start_date: "2010"
        end_date: "2012"
        title: "Full Stack Engineer"
        tags:
          [python, scala, sql, c++, pandas, ruby, elixir, rust, bigquery, mysql]
        summary: |
          Some text about the job summary.
          - I've done something
          - I've done another thing
          - Also I've done this thing
      - company: Coffee Factory
        start_date: "2010"
        end_date: "2016"
        title: "Full Stack Engineer"
        tags: [rails, nodejs, crytal, zig, javascript]
        summary: |
          Some text about the job summary.
          - I've done something
          - I've done another thing
          - Also I've done this thing
      - company: Freelancer
        start_date: "2016"
        title: "Full Stack Engineer"
        tags: [python, nim, rust, golang, perl, javascript, R, julia]
        summary: |
          Some text about the job summary.
          - I've done something
          - I've done another thing
          - Also I've done this thing
    education:
      # You can enter as many items you want here.
      - degree: Bachelors
        school: Yeditepe University, Istanbul
        field: Computer Science Engineering
        start_date: "2001"
        end_date: "2006"
        website: https://yeditepe.edu.tr/en
    # * using shared yaml variables
    skills: *common_skills
    languages:
      - name: English
        level: Fluent
    projects:
      - name: cap
        description: command line resume builder
        url: https://github.com/ceyhunkerti/cap
    # optional custom sections
    # items can have two attributes; `name` and `summary`
    custom_sections:
      - name: MY CUSTOM SECTION
        # this field accepts markdown syntax
        summary: |
          you can put some markdown here
          - I've done something
          - I've done another thing
          - Also I've done this thing
      - name: ANOTHER CUSTOM SECTION
        summary: |
          you can put some markdown here
          - I've done something
          - I've done another thing
          - Also I've done this thing
  # secondary resume
  my_resume_2:
    profile:
      name: William Antrim
      email: "william.antrim@bluecolor.io"
      phone: "+902888945017"
      title: Full Stack Engineer
      links:
        - "https://github.com/ceyhunkerti"
        - "https://github.com/bluecolor"
        - "https://en.wikipedia.org/wiki/Billy_the_Kid"
    summary: |
      Lorem ipsum dolor sit amet. Ut sapiente deleniti et nemo dolor sit nihil
      dolor aut repellendus repellat ad voluptas blanditiis nam nihil facilis et minus tempore?
      Qui rerum quis nam voluptas iure 33 iusto atque in ratione laudantium quo expedita animi et veniam nulla.
      - Ex provident maiores et minus soluta non voluptas temporibus.
      - Aut exercitationem architecto ea veritatis voluptates ea corrupti nesciunt ad nulla blanditiis.
      - Est saepe possimus vel deserunt consequatur.
    experiences:
      - company: ACME
        start_date: "2006"
        end_date: "2010"
        title: "Data Engineer"
        tags: [python, scala, sql]
        summary: |
          - You can enter markdown items
          - I've this thing
          - I've done another thing
          - Also I've done this thing
      - company: Chocolate Factory
        start_date: "2010"
        end_date: "2012"
        title: "Full Stack Engineer"
        tags:
          [python, scala, sql, c++, pandas, ruby, elixir, rust, bigquery, mysql]
        summary: |
          Some text about the job summary.
          - I've done something
          - I've done another thing
          - Also I've done this thing
      - company: Coffee Factory
        start_date: "2010"
        end_date: "2016"
        title: "Full Stack Engineer"
        tags: [rails, nodejs, crytal, zig, javascript]
        summary: |
          Some text about the job summary.
          - I've done something
          - I've done another thing
          - Also I've done this thing
      - company: Freelancer
        start_date: "2016"
        title: "Full Stack Engineer"
        tags: [python, nim, rust, golang, perl, javascript, R, julia]
        summary: |
          Some text about the job summary.
          - I've done something
          - I've done another thing
          - Also I've done this thing
    education:
      - degree: Bachelors
        school: Yeditepe University, Istanbul
        field: Computer Science Engineering
        start_date: 2001
        end_date: 2006
        website: https://yeditepe.edu.tr/en
    skills:
      - name: python
        level: Advanced
      - name: sql
        level: Advanced
      - name: javascript
        level: Advanced
      - name: golang
        level: Expert
    languages:
      - name: English
        level: Fluent
    projects:
      - name: cap
        description: command line resume builder
        url: https://github.com/ceyhunkerti/cap
    custom_sections:
      - name: MY CUSTOM SECTION
        summary: |
          you can put some markdown here
          - I've done something
          - I've done another thing
          - Also I've done this thing
      - name: ANOTHER CUSTOM SECTION
        summary: |
          you can put some markdown here
          - I've done something
          - I've done another thing
          - Also I've done this thing
  # you can add as many resumes as you want
  # - another_resume:
  # ....
  # - also_this_resume:
  # ....
  # - my_resume:
  # ...
